name: build-lint-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install postgres dependencies
      run: sudo apt-get update && sudo apt-get install -y libpq-dev
    - name: Check format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build
    - name: Install diesel
      run: cargo install diesel_cli --no-default-features --features postgres
    - name: Start DB
      run: docker run --name turtle-db -d -p 5432:5432 quay.io/mduarted/turtle-db
    - uses: nick-fields/retry@v2
      name: Runs migrations
      with:
        command: diesel migration run
        max_attempts: 3
        timeout_seconds: 45
      env:
        DATABASE_URL: postgresql://splinter:cheese@localhost:5432/turtles
    - name: Run tests
      run: cargo test --verbose
